services:
  db:
    image: postgres:15
    container_name: task_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./api
    container_name: task_backend
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: taskdb
      JWT_SECRET: secret
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./app/task-frontend
      dockerfile: Dockerfile
    container_name: task_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
