server {
  listen 80;
  server_name _;

  large_client_header_buffers 4 16k;
  underscores_in_headers on;

  root /usr/share/nginx/html;
  index index.html;


  location = /.well-known/appspecific/com.chrome.devtools.json {
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
